export { Header } from './Header'
export { Hero } from './Hero'
export { Footer } from './Footer'
export { InputCard } from './InputCard'
export { ErrorCard } from './ErrorCard'
export { OutputCard } from './OutputCard'
export { A4Page } from './A4Page'
